name: 01 - Building Blocks
on: [workflow_dispatch]

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
        - name: Say hello
          run: echo "Hello, world"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
        - name: Failed Step
          run: |
            echo "the job will fail"
            exit 0
       
        - name: Say Goodbye
          run: echo "Goodbye"