name: 04 - Using Actions
on: push

jobs:
    buiild:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Printing Folders
              run: tree .