name: 12 - Working with Outputs
on: 
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            name: ${{ steps.build.outputs.status}}
        steps:
            - name: Print GITHUB_OUTPUT
              run: echo $GITHUB_OUTPUT
            
            - name: Build
              id: build
              run: |
                echo status=${{ inputs.build-status }} >> "$GITHUB_OUTPUT"
                echo output1=value1 >> "$GITHUB_OUTPUT"
                echo output2=value2 >> "$GITHUB_OUTPUT"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.status == 'success' }}
        steps:
            - name: Deploy
              run: echo "Deploying"